### ISSUE TITLE
Support websocket

### ISSUE THREAD

**Issue by minuk-dev** [minuk-cluster/opampcommander#13]
## TODO

- [x] Make basic frame of websocket
- [ ] Define usecases:
  - [ ] Save websocketsession to send ServerToAgent message when newly update.
- [ ] Implement usecase.
- [ ] Make a event pipeline with redis to propagate update of agent by user & admin API for multiple api-server.:
  - When multiple otelcommander are deployed to handle many traffic like a k8s deployment, update of agent should be propagate to the proper server because opamp websocket connection is on a specific server for an agent. To acheive it, maybe use "Redis Event Notification" by `KeyspaceEventListener` (https://docs.spring.io/spring-data/data-redis/docs/current/api/org/springframework/data/redis/listener/KeyspaceEventMessageListener.html)
